### PR TITLE
D3 Upgrade

### PR DESCRIPTION
**Pull request by justinmc**
This upgrades D3 to v4.0.0.  The behavior is slightly changed where D3 behavior was changed, but the goal was to keep this as similar as possible to the original while updating D3.

### CODE REVIEW

**Comment by justinmc** [comment]
This is mostly working! 🎉  Still need to:

  - [ ] Get the example working with bipyridine data
  - [ ] Get it working in the notebook

**Comment by justinmc** [comment]
@avirshup Here's the general behavior after upgrading d3.  Does that work for you?  I think the main difference is that it sticks to the center now.

d3v4

**Comment by avirshup** [comment]
@justinmc That looks great!!! Much cleaner than before

**Comment by maxbates** [comment]
👍

**Pull request merged**
